### PR TITLE
Added buy button on front page

### PR DESCRIPTION
**Pull request by SeverinDK**

### CODE REVIEW

**Comment by peerchemist** [comment]
@bananenwilly @Sentinelrv @saeveritt  what do you think?

**Comment by bananenwilly** [comment]
Screenshot_20210529-134714_Firefox
Double text in German?

**Comment by SeverinDK** [comment]
> Screenshot_20210529-134714_Firefox
> Double text in German?

Good catch. Fix in https://github.com/peercoin/peercoin.net/pull/238

**Comment by bananenwilly** [comment]
Please commit that fix to this PR. Having another PR to fix your initial PR is not very handy.

**Comment by SeverinDK** [comment]
> Please commit that fix to this PR. Having another PR to fix your initial PR is not very handy.

This pr did not introduce that mistake. It was done in https://github.com/peercoin/peercoin.net/pull/232

**Comment by bananenwilly** [comment]
grafik

would need some margin/padding on mobile

**Comment by SeverinDK** [comment]
What device does that happen on @bananenwilly? I cannot reproduce it, neither on an Android device or when simulating device screens in Chrome. I can only get it to look like this if the `min-height: 100vh;` rule on the .hero class is removed.

viber_image_2021-05-29_19-14-58
Capture

**Comment by bananenwilly** [comment]
try any height smaller than ~400 px

**Comment by SeverinDK** [comment]
Capture
Made a few modifications to the .hero rules and this is what it looks like on tiny screens now.

**Comment by bananenwilly** [comment]
fixed now. 

another suggestion: 
.hero  &__description {

    @include viewports(up-to tiny) {
      width: 100%;
      **padding: 0 1rem;**
    }

makes the description a little less cramped. This was also probably introduced with another PR but I just noticed it being problematic on screens < 370 px without the padding.

**Pull request closed without merging**
