### PR TITLE
Removed empty renderHTML

### PR DESCRIPTION
**Pull request by blrhc**
Screenshot 2021-02-14 at 22 40 20

Just noticed there was a small error at the end here, so have removed the empty section.

### CODE REVIEW

**Comment by blrhc** [comment]
@bananenwilly Is this OK to merge?

**Comment by peerchemist** [comment]
Yep, all good.

**Comment by blrhc** [comment]
> Yep, all good.

Oops, sorry, are you the best person to tag for this kind of thing?
I can't request reviews for some reason...

**Comment by peerchemist** [comment]
Just leave PR open whoever finds himself online will check it out and review. A number of people have write access to this repo.

**Pull request merged**
