### PR TITLE
Change Twitter image to X

### PR DESCRIPTION
**Pull request by sandakersmann**
Change Twitter image to X

### CODE REVIEW

**Comment by sandakersmann** [comment]
@willyfromtheblock Saw that some translation stuff needed to be changed to do a full rebranding, so thought it would be best to leave that to you :)

**Comment by willyfromtheblock** [comment]
Yes, it is very unfortunate with the links...

**Comment by willyfromtheblock** [comment]
can you maybe scale this one down as well?
grafik

**Comment by sandakersmann** [comment]
Don't think I can do much better without reducing the resolution.

**Pull request closed without merging**
