### PR TITLE
add mobile wallet links to wallet page

### PR DESCRIPTION
**Pull request by bananenwilly**
- prettier doing things
- add official mobile wallet links to app store and play store

@peerchemist @SeverinDK 
please review, I will merge it when the apps are live in the stores

### CODE REVIEW

**Comment by bananenwilly** [comment]
alternative icons/badges:
https://developer.apple.com/app-store/marketing/guidelines/#section-badges
https://play.google.com/intl/en_us/badges/

**Comment by peerchemist** [comment]
Would prefer alternative badges honestly.

**Comment by bananenwilly** [comment]
Okay, than we need a legal page as well where we make attributions to Google and apple for using their stuff

**Comment by peerchemist** [comment]
Ah, then no.

**Review by peerchemist — APPROVED** [review]
Let's go.

**Pull request merged**
