### PR TITLE
Update to 2021 logos

### PR DESCRIPTION
**Pull request by sandakersmann**
Update to 2021 logos

### CODE REVIEW

**Comment by sandakersmann** [comment]
@peerchemist Please merge :)

**Comment by bananenwilly** [comment]
@Sentinelrv can you confirm that presently (live on peercoin.net) the logos on the website are up to date?

**Comment by sandakersmann** [comment]
@bananenwilly If the performance hit is a great concern I can scale down the images later.

**Comment by sandakersmann** [comment]
@bananenwilly @peerchemist Sentinelrv has confirmed that these are the correct logos. I have also scaled down the logos in the webfixed folder. Please merge :)

**Review by bananenwilly — APPROVED** [review]

**Pull request merged**
