### PR TITLE
redirects and proxies for docs and university

### PR DESCRIPTION
**Pull request by willyfromtheblock**

### CODE REVIEW

**Comment by willyfromtheblock** [comment]
https://edf74407.peercoin-net.pages.dev/bin/peercoinpaper.pdf

points to 
/whitepapers/peercoin-paper.pdf

**Comment by peerchemist** [comment]
Looks good. Anything else we should test out?

**Comment by willyfromtheblock** [comment]
@peerchemist lgtm

**Review by peerchemist — APPROVED** [review]
k

**Pull request merged**
